### ISSUE TITLE
Checklist: core exercise mentor notes

### ISSUE THREAD

**Issue by SleeplessByte** [exercism/typescript#239]
Mentor notes should be written here: [website-copy/tracks/typescript](https://github.com/exercism/website-copy/tree/master/tracks/typescript/exercises)

- [x] [leap](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/leap/mentoring.md)
- [ ] [simple-cipher](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/simple-cipher/mentoring.md)
- [ ] [rna-transcription](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/rna-transcription/mentoring.md)
- [ ] [bob](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/bob/mentoring.md)
- [x] [pangram](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/pangram/mentoring.md)
- [x] [space-age](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/space-age/mentoring.md)
- [ ] [prime-factors](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/prime-factors/mentoring.md)
- [x] [matrix](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/matrix/mentoring.md)
- [x] [linked-list](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/linked-list/mentoring.md)
- [ ] [secret-handshake](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/secret-handshake/mentoring.md)
- [ ] [robot-name](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/robot-name/mentoring.md)
- [x] [grade-school](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/grade-school/mentoring.md)
- [ ] [wordy](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/wordy/mentoring.md)
- [ ] [list-ops](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/list-ops/mentoring.md)
- [ ] [clock](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/clock/mentoring.md)
- [x] [pascals-triangle](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/pascals-triangle/mentoring.md)
- [ ] [rational-numbers](https://github.com/exercism/website-copy/tree/master/tracks/typescript/exercises/rational-numbers)
- [ ] [binary-search](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/binary-search/mentoring.md)
- [ ] [atbash-cipher](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/atbash-cipher/mentoring.md)

Non-core exercises with notes:
- [x] [gigasecond](https://github.com/exercism/website-copy/blob/master/tracks/typescript/exercises/gigasecond/mentoring.md)

If you are writing mentor notes, please dibs it here so people don't do double work! Check the open PRs for [mentor-notes](https://github.com/exercism/website-copy/pulls?q=is%3Aopen+is%3Apr+label%3Atype%2Fmentor-notes) before you start as well!

**Comment by senpl** [comment]
Notes for two-fer exercise should be added ???

**Comment by SleeplessByte** [comment]
@senpl https://github.com/exercism/website-copy/pull/1087
