### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/typescript#403]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/typescript/issues/394)
- [x] [Add key features](https://github.com/exercism/typescript/issues/395)
- [x] [Add tags](https://github.com/exercism/typescript/issues/396)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/typescript/issues/397)
- [x] [Update status of track](https://github.com/exercism/typescript/issues/401)
- [x] [Update status of Concept Exercises](https://github.com/exercism/typescript/issues/402)
- [x] [Pass linting checks](https://github.com/exercism/typescript/issues/398)
- [x] [Build Test Runner](https://github.com/exercism/typescript/issues/399)
- [x] [Build Analyzer and Representer](https://github.com/exercism/typescript/issues/400) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
